#!/usr/bin/env python3
"""
Regenerate src/encodings.rs from the IANA character set registry.
"""
import csv
import io
import subprocess
import sys
from pathlib import Path

REGISTRY = "https://www.iana.org/assignments/character-sets/character-sets-1.csv"

# GDAL's spelling, the IANA record its aliases come from, and the Rust constant name.
# Covers every encoding any GDAL version converts: the first three come from cpl_recode_stub.cpp,
# the rest from cpl_character_sets.c, added in 3.10.
SUPPORTED = [
    ("UTF-8", "UTF-8", "UTF8"),
    ("ISO-8859-1", "ISO_8859-1:1987", "LATIN1"),
    ("CP437", "IBM437", "CP437"),
    ("CP1250", "windows-1250", "CP1250"),
    ("CP1251", "windows-1251", "CP1251"),
    ("CP1252", "windows-1252", "CP1252"),
    ("ISO-8859-2", "ISO_8859-2:1987", "LATIN2"),
    ("ISO-8859-15", "ISO-8859-15", "LATIN9"),
]


def records(text):
    out = {}
    for row in csv.DictReader(io.StringIO(text)):
        name = (row.get("Name") or "").strip()
        if name:
            out[name] = [a.strip() for a in (row.get("Aliases") or "").splitlines() if a.strip()]
    return out


def main():
    text = subprocess.run(["curl", "-sS", "--max-time", "30", REGISTRY],
                          capture_output=True, text=True, check=True).stdout
    by_name = records(text)

    lines = [
        "// Generated by scripts/generate-encodings.py. Do not edit.",
        "// IANA character set registry: https://www.iana.org/assignments/character-sets/character-sets.xhtml",
        "",
    ]
    # emitted in constant-name order; SUPPORTED stays grouped by where GDAL implements each
    supported = sorted(SUPPORTED, key=lambda entry: entry[2])
    for gdal_name, _, konst in supported:
        lines.append(f'pub(crate) const {konst}: &str = "{gdal_name}";')
    lines += ["", "pub(crate) const ALIASES: &[(&str, &str)] = &["]

    seen = set()
    for gdal_name, iana_name, konst in supported:
        if iana_name not in by_name:
            sys.exit(f"{iana_name} is not in the registry")
        # IANA does not register GDAL's own spelling for every encoding, "CP1252" among them.
        for spelling in [iana_name] + by_name[iana_name] + [gdal_name]:
            key = spelling.upper()
            if key in seen:
                continue
            seen.add(key)
            lines.append(f'    ("{spelling}", {konst}),')
    lines += ["];", ""]

    Path("src/encodings.rs").write_text("\n".join(lines))
    print(f"wrote src/encodings.rs: {len(seen)} spellings from {len(by_name)} registry records")


if __name__ == "__main__":
    main()
