// Generated by scripts/generate-encodings.py. Do not edit.
// IANA character set registry: https://www.iana.org/assignments/character-sets/character-sets.xhtml

pub(crate) const CP1250: &str = "CP1250";
pub(crate) const CP1251: &str = "CP1251";
pub(crate) const CP1252: &str = "CP1252";
pub(crate) const CP437: &str = "CP437";
pub(crate) const LATIN1: &str = "ISO-8859-1";
pub(crate) const LATIN2: &str = "ISO-8859-2";
pub(crate) const LATIN9: &str = "ISO-8859-15";
pub(crate) const UTF8: &str = "UTF-8";

pub(crate) const ALIASES: &[(&str, &str)] = &[
    ("windows-1250", CP1250),
    ("cswindows1250", CP1250),
    ("CP1250", CP1250),
    ("windows-1251", CP1251),
    ("cswindows1251", CP1251),
    ("CP1251", CP1251),
    ("windows-1252", CP1252),
    ("cswindows1252", CP1252),
    ("CP1252", CP1252),
    ("IBM437", CP437),
    ("cp437", CP437),
    ("437", CP437),
    ("csPC8CodePage437", CP437),
    ("ISO_8859-1:1987", LATIN1),
    ("iso-ir-100", LATIN1),
    ("ISO_8859-1", LATIN1),
    ("ISO-8859-1", LATIN1),
    ("latin1", LATIN1),
    ("l1", LATIN1),
    ("IBM819", LATIN1),
    ("CP819", LATIN1),
    ("csISOLatin1", LATIN1),
    ("ISO_8859-2:1987", LATIN2),
    ("iso-ir-101", LATIN2),
    ("ISO_8859-2", LATIN2),
    ("ISO-8859-2", LATIN2),
    ("latin2", LATIN2),
    ("l2", LATIN2),
    ("csISOLatin2", LATIN2),
    ("ISO-8859-15", LATIN9),
    ("ISO_8859-15", LATIN9),
    ("Latin-9", LATIN9),
    ("csISO885915", LATIN9),
    ("UTF-8", UTF8),
    ("csUTF8", UTF8),
];
